//! HTML reporter — self-contained `report.html` for browser viewing.
//!
//! Renders a [`Report`] into a single HTML5 document with inline CSS + inline
//! SVG charts. Designed to open straight from `file://` — no external CDN, no
//! JavaScript, no network fetches. Closes the IBM/spbiju competitive gap.
//!
//! The latency chart is rendered from the percentile anchors exposed via
//! `LatencyStats` (raw hdrhistogram buckets aren't surfaced through the locked
//! [`Report`] type). Bar heights are interpolated between adjacent CDF anchors
//! — representative shape, not bucket-exact. The chart section is omitted when
//! no latency samples were recorded.

use std::borrow::Cow;
use std::fmt::Write as _;
use std::time::Duration;

use crate::report::common::{describe_failure, fmt_count, fmt_duration, format_server_command};
use crate::report::{
    Report, ReportError, Reporter, ThresholdKind, ThresholdViolation, format_iso8601_utc,
};

mod chart;
mod css;

use chart::write_latency_chart;
use css::CSS;

/// HTML reporter. Self-contained single-file output (no external assets).
///
/// Stateless and zero-cost; clone freely. See module docs for output shape.
#[derive(Debug, Default, Clone, Copy)]
pub struct HtmlReporter;

impl Reporter for HtmlReporter {
    fn render(&self, report: &Report) -> Result<String, ReportError> {
        render_inner(report).map_err(|e| ReportError::Other(format!("html render: {e}")))
    }
}

fn render_inner(report: &Report) -> Result<String, std::fmt::Error> {
    let mut out = String::with_capacity(4096);
    write_doc_open(&mut out, report)?;
    write_header(&mut out, report)?;
    write_summary(&mut out, report)?;
    write_latency_chart(&mut out, report)?;
    write_per_tool(&mut out, report)?;
    write_violations(&mut out, &report.threshold_violations)?;
    let version = env!("CARGO_PKG_VERSION");
    let ts = format_iso8601_utc(report.started_at);
    write!(
        out,
        "<footer>Generated by mcp-loadtest v{version} · run started {ts}</footer></div></body></html>",
    )?;
    Ok(out)
}

fn write_doc_open(out: &mut String, report: &Report) -> std::fmt::Result {
    let title = escape_html(&report.run_id);
    out.push_str(
        "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><title>mcp-loadtest run ",
    );
    out.push_str(&title);
    out.push_str("</title><style>");
    out.push_str(CSS);
    out.push_str("</style></head><body><div class=\"wrap\">");
    Ok(())
}

fn write_header(out: &mut String, report: &Report) -> std::fmt::Result {
    let (badge_class, badge_text) = if report.passed() {
        ("pass", "Pass".to_string())
    } else {
        ("fail", format!("Fail — {}", describe_failure(report)))
    };
    let server_raw = format_server_command(report);
    let server = escape_html(&server_raw);
    let started = format_iso8601_utc(report.started_at);
    let scenario = escape_html(&report.scenario_name);
    let run_id = escape_html(&report.run_id);
    let badge_text = escape_html(&badge_text);
    write!(
        out,
        "<header><h1>mcp-loadtest run <span class=\"mono\">{run_id}</span></h1>\
<div class=\"meta\"><span class=\"badge {badge_class}\">{badge_text}</span> \
&nbsp;<strong>Scenario:</strong> {scenario} \
&nbsp;<strong>Server:</strong> <code>{server}</code> \
&nbsp;<strong>Started:</strong> {started}</div></header>",
    )
}

fn write_summary(out: &mut String, report: &Report) -> std::fmt::Result {
    let lat = &report.metrics.latency;
    let tp = &report.metrics.throughput;
    let total = tp.total_requests;
    let errors = total.saturating_sub(tp.successful_requests);
    let deadlocks = report.scenario_outcome.deadlock_count;
    let v = &report.threshold_violations;
    out.push_str("<h2>Summary</h2><table><thead><tr>");
    out.push_str("<th>p50</th><th>p95</th><th>p99</th><th>p999</th>");
    out.push_str("<th class=\"num\">req/s</th><th class=\"num\">total</th>");
    out.push_str("<th class=\"num\">errors</th><th class=\"num\">deadlocks</th>");
    out.push_str("</tr></thead><tbody><tr>");
    push_latency_cell(out, ThresholdKind::P50Latency, lat.p50, v);
    push_latency_cell(out, ThresholdKind::P95Latency, lat.p95, v);
    push_latency_cell(out, ThresholdKind::P99Latency, lat.p99, v);
    push_latency_cell(out, ThresholdKind::P999Latency, lat.p999, v);
    write!(out, "<td class=\"num\">{:.2}</td>", tp.requests_per_sec)?;
    write!(out, "<td class=\"num\">{}</td>", fmt_count(total))?;
    write!(out, "<td class=\"num\">{}</td>", fmt_count(errors))?;
    write!(
        out,
        "<td class=\"num\">{deadlocks}</td></tr></tbody></table>"
    )
}

fn push_latency_cell(
    out: &mut String,
    kind: ThresholdKind,
    value: Duration,
    vs: &[ThresholdViolation],
) {
    let value_str = fmt_duration(value);
    let s = escape_html(&value_str);
    if vs.iter().any(|v| v.kind == kind) {
        let _ = write!(
            out,
            "<td class=\"num\" style=\"color:#991b1b;font-weight:600;\">{s}</td>"
        );
    } else {
        let _ = write!(out, "<td class=\"num\">{s}</td>");
    }
}

fn write_per_tool(out: &mut String, report: &Report) -> std::fmt::Result {
    // `Report` doesn't expose per-tool latency snapshots directly. The closest
    // accessible surface is `coverage.exercised`, a name→call-count map
    // populated from `Recorder::snapshot_per_tool`. We render that as the
    // per-tool breakdown to honour "no new Report fields".
    let Some(coverage) = &report.coverage else {
        return Ok(());
    };
    if coverage.exercised.is_empty() {
        return Ok(());
    }
    out.push_str("<h2>Per-tool breakdown</h2><table><thead><tr><th>tool</th><th class=\"num\">calls</th></tr></thead><tbody>");
    for (name, calls) in &coverage.exercised {
        let n = escape_html(name);
        write!(
            out,
            "<tr><td class=\"mono\">{n}</td><td class=\"num\">{}</td></tr>",
            fmt_count(*calls)
        )?;
    }
    out.push_str("</tbody></table>");
    if !coverage.unexercised.is_empty() {
        out.push_str("<p class=\"meta\">Unexercised: ");
        let mut first = true;
        for name in &coverage.unexercised {
            if !first {
                out.push_str(", ");
            }
            first = false;
            let _ = write!(out, "<code>{}</code>", escape_html(name));
        }
        out.push_str("</p>");
    }
    Ok(())
}

fn write_violations(out: &mut String, violations: &[ThresholdViolation]) -> std::fmt::Result {
    if violations.is_empty() {
        return Ok(());
    }
    out.push_str("<h2>Threshold violations</h2><table><thead><tr><th>metric</th><th>expected</th><th>actual</th></tr></thead><tbody>");
    for v in violations {
        let metric = escape_html(v.kind.name());
        let expected = escape_html(&v.expected);
        let actual = escape_html(&v.actual);
        write!(
            out,
            "<tr class=\"violation\"><td>{metric}</td><td>{expected}</td><td class=\"num\">{actual}</td></tr>",
        )?;
    }
    out.push_str("</tbody></table>");
    Ok(())
}

/// Minimal HTML entity escaper for `&<>"'`. Returns the input unchanged when
/// no escaping is needed so the common path doesn't allocate. Pulled in-crate
/// since the workspace doesn't depend on `html_escape`.
pub(super) fn escape_html(s: &str) -> Cow<'_, str> {
    if !s
        .bytes()
        .any(|b| matches!(b, b'&' | b'<' | b'>' | b'"' | b'\''))
    {
        return Cow::Borrowed(s);
    }
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            other => out.push(other),
        }
    }
    Cow::Owned(out)
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;
    use std::time::{Duration, SystemTime};

    use crate::report::{
        ProcessStats, Report, Reporter, ServerInfo, ThresholdKind, ThresholdViolation,
    };
    use mcp_loadtest_core::coverage::CoverageReport;
    use mcp_loadtest_core::metrics::{
        LatencyStats, OutcomeCounts, ScenarioMetrics, ThroughputStats,
    };
    use mcp_loadtest_core::outcome::ScenarioOutcome;

    use super::*;

    fn skeleton_report() -> Report {
        Report {
            run_id: "01HXYHTML000000000000000000".into(),
            started_at: SystemTime::UNIX_EPOCH,
            duration: Duration::from_secs(1),
            scenario_name: "sustained".into(),
            server_info: ServerInfo {
                command: "python".into(),
                args: vec!["-m".into(), "my_mcp".into()],
                pid: None,
                protocol_version: None,
            },
            metrics: ScenarioMetrics::default(),
            process: ProcessStats::default(),
            scenario_outcome: ScenarioOutcome::default(),
            trace_path: None,
            threshold_violations: Vec::new(),
            coverage: None,
        }
    }

    #[test]
    fn renders_empty_report_without_panic() {
        let html = HtmlReporter.render(&skeleton_report()).unwrap();
        assert!(html.contains("<html"), "missing <html");
        assert!(html.contains("</html>"), "missing </html>");
        assert!(
            html.contains("01HXYHTML000000000000000000"),
            "missing run_id"
        );
        // No latency samples → no chart section.
        assert!(!html.contains("Latency distribution"));
    }

    #[test]
    fn escapes_html_in_tool_names() {
        let mut r = skeleton_report();
        let mut exercised = BTreeMap::new();
        exercised.insert("<script>alert(1)</script>".to_string(), 7);
        r.coverage = Some(CoverageReport::build(
            vec!["<script>alert(1)</script>".to_string()],
            exercised,
        ));
        r.server_info.command = "python\"--evil".into();
        r.scenario_name = "a & b".into();
        let html = HtmlReporter.render(&r).unwrap();
        assert!(
            html.contains("&lt;script&gt;"),
            "script tag should be escaped"
        );
        assert!(
            !html.contains("<script>alert(1)</script>"),
            "literal script tag leaked"
        );
        assert!(html.contains("&quot;"), "missing escaped quote");
        assert!(html.contains("a &amp; b"), "missing escaped ampersand");
    }

    #[test]
    fn histogram_renders_svg_when_data_present() {
        let mut r = skeleton_report();
        r.metrics = ScenarioMetrics {
            latency: LatencyStats {
                p50: Duration::from_micros(12_300),
                p95: Duration::from_micros(45_600),
                p99: Duration::from_micros(123_400),
                p999: Duration::from_micros(456_700),
                mean: Duration::from_micros(23_400),
                min: Duration::from_micros(1_200),
                max: Duration::from_micros(999_900),
                count: 12_345,
            },
            throughput: ThroughputStats {
                total_requests: 12_345,
                successful_requests: 12_300,
                requests_per_sec: 205.75,
            },
            outcomes: OutcomeCounts::default(),
        };
        let html = HtmlReporter.render(&r).unwrap();
        assert!(html.contains("<svg"), "missing <svg");
        assert!(html.contains("Latency distribution"));
        assert!(html.contains("<rect "), "expected histogram bars");
    }

    #[test]
    fn threshold_violation_row_styled_when_present() {
        let mut r = skeleton_report();
        r.threshold_violations.push(ThresholdViolation {
            kind: ThresholdKind::P99Latency,
            expected: "<= 100ms".into(),
            actual: "234ms".into(),
        });
        let html = HtmlReporter.render(&r).unwrap();
        assert!(html.contains("violation"));
        assert!(
            html.contains("&lt;= 100ms"),
            "expected condition should be escaped"
        );
        assert!(html.contains("Threshold violations"));
        assert!(html.contains("badge fail"));
    }

    #[test]
    fn trivial_string_is_borrowed_unchanged() {
        match escape_html("hello world 123") {
            Cow::Borrowed(b) => assert_eq!(b, "hello world 123"),
            Cow::Owned(_) => panic!("expected borrowed, got owned"),
        }
    }
}
